/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_knowm_waveforms4j_DWF_AnalogTriggerType */

#ifndef _Included_org_knowm_waveforms4j_DWF_AnalogTriggerType
#define _Included_org_knowm_waveforms4j_DWF_AnalogTriggerType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
