/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_knowm_waveforms4j_DWF_AnalogOutIdle */

#ifndef _Included_org_knowm_waveforms4j_DWF_AnalogOutIdle
#define _Included_org_knowm_waveforms4j_DWF_AnalogOutIdle
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
